language: python

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "pypy"

install:
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - tox

after_success:
  # Coveralls submission only for py35 environment, because of being the only
  # one that executes doctest-modules testing, according to tox.ini.
  - if [[ $ENV == python=3.5* ]]; then coveralls; fi
